"""Добавление столбца category в таблицу products

Revision ID: 56a285b35b13
Revises: 
Create Date: 2025-09-07 16:02:18.328483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a285b35b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.Enum('APPAREL', 'ELECTRONICS', 'HOME', 'BEAUTY', name='category'), nullable=False))
    op.add_column('products', sa.Column('discount_percent', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percent')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
