"""ADd cascade, all-orphan в таблице PRODUCT

Revision ID: 670ce3208d38
Revises: 8d3b6b5b90c5
Create Date: 2025-09-18 20:02:10.128553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670ce3208d38'
down_revision: Union[str, Sequence[str], None] = '8d3b6b5b90c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
