"""Добавление столбца category в таблицу products

Revision ID: 77ed6f415080
Revises: 56a285b35b13
Create Date: 2025-09-08 09:13:20.253581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ed6f415080'
down_revision: Union[str, Sequence[str], None] = '56a285b35b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE orderstatus AS ENUM ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED');")
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus', create_type=False), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###
