"""ADd cascade, all-orphan в таблице PRODUCT

Revision ID: 8d3b6b5b90c5
Revises: a0ba3efcd61e
Create Date: 2025-09-18 19:58:51.471734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3b6b5b90c5'
down_revision: Union[str, Sequence[str], None] = 'a0ba3efcd61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
