"""Добавление Cascade all в product_id

Revision ID: a0ba3efcd61e
Revises: a135913afce2
Create Date: 2025-09-18 19:50:57.226817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ba3efcd61e'
down_revision: Union[str, Sequence[str], None] = 'a135913afce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
