"""Добавление столбца create_at в Products

Revision ID: bf868dfc3117
Revises: 77ed6f415080
Create Date: 2025-09-08 23:05:23.433536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf868dfc3117'
down_revision: Union[str, Sequence[str], None] = '77ed6f415080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
