"""Обнавлние таблиц

Revision ID: d7c1fae4df98
Revises: e4cd0c4a4d15
Create Date: 2025-09-18 15:10:25.540267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c1fae4df98'
down_revision: Union[str, Sequence[str], None] = 'e4cd0c4a4d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basketcart', sa.Column('price_with_discount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basketcart', 'price_with_discount')
    # ### end Alembic commands ###
